apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCUdVfRdkKcCuwKEKbFJxzL0FvRg7kaMcOBHJR4Bnu1gMnRKn8ZqKqAiZBjCzB+w71m7156nC49dpHMp601w86Ev7tvgxp/NiqMae5ntnbGMeHQI4HgmHX5DpJK8R3bKQkUhI3CiGD/z6ImMPm2z8aWH4pC1zm1FGEyar4pNM5W70P1z4PyReTs29I27v3FZ87/+OsggtHvdiQygn7DxJMCotvIg1ZdMxaP5tWAdsJTV+GXC0QtMk3W5og2RM51MM9ByX/1uYK4iSfPQPM7T09f1pHMivzO0BtwIi+JOhZ8CR6LOQJD3XuOKZYc9P3LnXWaFLK60JhYpdtIlkG4BkN2uPY/i95vUS8OjPtAqf2VxDYJrtEcvgj88NsEwJaci5nz7B8YnJBRlCQJ9sLNM0WvilVvI9duOJQUxFIoN5HFRzdTLrhgree/0uJT3c5q4Fw/fu00lcRWzxdN7+7evDSOq5YClKYedD7cwLfNGXSC8d1YguDGR2m04A6sq7NEmSmXsW3eKk09WgDqZ7CdHxCfPlwPVV70KC5Q+F8onQ5TYJdh8X1/wnb+mOlFTuqDsOpMs18Xq3MQbNNLRdoP+UWV58HJR8AXU6lRg2bosXQPT4xgsxSeZu/XxSH7bmkbudhioC1Y1WOIaD9bmYUlKRSZZNPZjSrfOxQSPvnT05JfNhx0hvosYF6+AnH8H6a8FRoxEIQSCtfP+R6WqpleV9/W/LN8RwXKIrTr
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

